# Generated by Django 3.2.6 on 2021-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(blank=True, max_length=250, null=True)),
                ('published_date', models.CharField(blank=True, max_length=30, null=True)),
                ('categories', models.CharField(blank=True, max_length=250, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
